name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the code
        uses: actions/checkout@v4

      - name: Setting up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Running tests
        run: go test -cover ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the code
        uses: actions/checkout@v4

      - name: Setting up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Installing Statickcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Checking formatting
        run: test -z $(go fmt ./...)

      - name: Checking linting
        run: staticcheck ./...
